### ISSUE TITLE
Configuration with name 'default' not found

### ISSUE THREAD

**Issue by jam0cam** [HyphenateInc/IMDemo_android#17]
I cloned the project, imported into Android Studio 2.2, and got this error. 

![image](https://cloud.githubusercontent.com/assets/869467/19016046/196604c4-87de-11e6-8137-22c681bfb041.png)

**Comment by jam0cam** [comment]
Turns out you have to also clone this project, and put it on the same directory level as the demo project. 

https://github.com/HyphenateInc/Hyphenate-EaseUI-Android

**Comment by jerrywu12** [comment]
@jam0cam So that simple project might be out of date, since the latest project is using the SDK 3.1.5, but if you replace the simple demo project folder with the latest project (demo-android) you were working earlier, then it should compiles fine. The 'default' thing is looking for EaseUI library. 
However, let me check with the engineering team, to see if we can make it simpler in the future.
